/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

namespace std { template <> struct hash<CE_NS ColliderType> { size_t operator() (const CE_NS ColliderType &t) const { return size_t(t); } }; }

CE_BEGIN_NAMESPACE

const std::unordered_map<ColliderType, std::string> ColliderTypeStr = {
	{ ColliderType::InfPlane, "InfPlane" },
	{ ColliderType::Plane, "Plane" },
	{ ColliderType::Sphere, "Sphere" },
	{ ColliderType::Cube, "Cube" },
	{ ColliderType::Capsule, "Capsule" },
	{ ColliderType::Mesh, "Mesh" }
};

CE_END_NAMESPACE
