/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

CE_BEGIN_NAMESPACE

const std::unordered_map<ColliderType, std::string> ColliderTypeStr = {
	{ ColliderType::InfPlane, "InfPlane" },
	{ ColliderType::Plane, "Plane" },
	{ ColliderType::Sphere, "Sphere" },
	{ ColliderType::Cube, "Cube" },
	{ ColliderType::Capsule, "Capsule" },
	{ ColliderType::Mesh, "Mesh" },
	{ ColliderType::_COUNT, "_COUNT" }
};

CE_END_NAMESPACE
