/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

CE_BEGIN_NAMESPACE

const std::unordered_map<ComponentType, std::string> ComponentTypeStr = {
	{ ComponentType::Animator, "Animator" },
	{ ComponentType::Camera, "Camera" },
	{ ComponentType::Light, "Light" },
	{ ComponentType::LightProbe, "LightProbe" },
	{ ComponentType::MeshRenderer, "MeshRenderer" },
	{ ComponentType::Rig, "Rig" },
	{ ComponentType::Script, "Script" },
	{ ComponentType::_COUNT, "_COUNT" },
	{ ComponentType::Unknown, "Unknown" }
};

CE_END_NAMESPACE
