/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

CE_BEGIN_NAMESPACE

const std::unordered_map<LightType, std::string> LightTypeStr = {
	{ LightType::Point, "Point" },
	{ LightType::Spot, "Spot" },
	{ LightType::Directional, "Directional" }
};

CE_END_NAMESPACE
