/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

namespace std { template <> struct hash<CE_NS LightFalloff> { size_t operator() (const CE_NS LightFalloff &t) const { return size_t(t); } }; }

CE_BEGIN_NAMESPACE

const std::unordered_map<LightFalloff, std::string> LightFalloffStr = {
	{ LightFalloff::Constant, "Constant" },
	{ LightFalloff::Linear, "Linear" },
	{ LightFalloff::Squared, "Squared" }
};

CE_END_NAMESPACE
