/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

CE_BEGIN_NAMESPACE

const std::unordered_map<LightFalloff, std::string> LightFalloffStr = {
	{ LightFalloff::Constant, "Constant" },
	{ LightFalloff::Linear, "Linear" },
	{ LightFalloff::Squared, "Squared" }
};

CE_END_NAMESPACE
