/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

namespace std { template <> struct hash<CE_NS LightType> { size_t operator() (const CE_NS LightType &t) const { return size_t(t); } }; }

CE_BEGIN_NAMESPACE

const std::unordered_map<LightType, std::string> LightTypeStr = {
	{ LightType::Point, "Point" },
	{ LightType::Spot, "Spot" },
	{ LightType::Directional, "Directional" }
};

CE_END_NAMESPACE
