/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

CE_BEGIN_NAMESPACE

const std::unordered_map<ParticleEmissionShape, std::string> ParticleEmissionShapeStr = {
	{ ParticleEmissionShape::Cone, "Cone" },
	{ ParticleEmissionShape::Rectangle, "Rectangle" },
	{ ParticleEmissionShape::Sphere, "Sphere" }
};

CE_END_NAMESPACE
