/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

CE_BEGIN_NAMESPACE

const std::unordered_map<CameraClearType, std::string> CameraClearTypeStr = {
	{ CameraClearType::None, "None" },
	{ CameraClearType::Depth, "Depth" },
	{ CameraClearType::Color, "Color" },
	{ CameraClearType::ColorAndDepth, "ColorAndDepth" }
};

CE_END_NAMESPACE
