/*
 * Interface for running projects generated by ChokoEditor
 * Use ChokoLait if you are writing header-only programs
 */

#pragma once
#include "chokolait.hpp"
#include "ce2/player_defines.hpp"

CE_BEGIN_PL_NAMESPACE

class ChokoPlayer {
	static void Init();

public:
	static std::string dataPath;

	static void Main();
};

CE_END_PL_NAMESPACE

#include "ce2/player_includes.hpp"
