/*
 * Generated by the preprocessor script
 * DO NOT EDIT
 */
#pragma once
#include "chokoengine.hpp"

CE_BEGIN_NAMESPACE

const std::unordered_map<LightProbeUpdateFrequency, std::string> LightProbeUpdateFrequencyStr = {
	{ LightProbeUpdateFrequency::OnStart, "OnStart" },
	{ LightProbeUpdateFrequency::Realtime, "Realtime" }
};

CE_END_NAMESPACE
